import { AgentDefinition } from './agent.types';

export const AGENT_REGISTRY: AgentDefinition[] = [
  {
    id: 'fcx-agent-master',
    name: 'FCX Agent Master',
    role: 'master',
    domain: 'orchestration',
    capabilities: ['classify-task', 'route-task', 'coordinate-specialists', 'enforce-approval-gates'],
    tools: ['agent.registry', 'agent.decision-log', 'agent.approvals'],
    constraints: ['must-log-routing-decisions', 'must-not-bypass-approval-gates', 'must-not-expose-secrets'],
    requiresHumanApprovalFor: ['critical-action', 'deployment'],
  },
  {
    id: 'fcx-software-engineering-agent',
    name: 'FCX Software Engineering Agent',
    role: 'specialist',
    domain: 'engineering',
    capabilities: ['codebase-analysis', 'implementation', 'testing', 'refactoring'],
    tools: ['repository', 'build', 'lint', 'test'],
    constraints: ['preserve-existing-code', 'must-validate-changes', 'no-deployment-without-approval'],
    requiresHumanApprovalFor: ['breaking-change', 'deployment'],
  },
  {
    id: 'fcx-strategic-council',
    name: 'FCX Strategic Council',
    role: 'specialist',
    domain: 'strategy',
    capabilities: ['architecture-review', 'roadmap-analysis', 'risk-governance'],
    tools: ['architecture.context', 'decision.registry'],
    constraints: ['advisory-only', 'must-declare-assumptions'],
    requiresHumanApprovalFor: ['architecture-change', 'budget-commitment'],
  },
  {
    id: 'fcx-industrial-agent',
    name: 'FCX Industrial Agent',
    role: 'specialist',
    domain: 'industrial',
    capabilities: ['asset-diagnostics', 'telemetry-analysis', 'alarm-analysis', 'maintenance-recommendation'],
    tools: ['assets', 'telemetry', 'alarms', 'predictive', 'work-orders'],
    constraints: ['must-cite-operational-evidence', 'no-critical-intervention-without-human'],
    requiresHumanApprovalFor: ['critical-intervention', 'work-order-execution'],
  },
  {
    id: 'fcx-trade-intelligence-agent',
    name: 'FCX Trade Intelligence Agent',
    role: 'specialist',
    domain: 'trade',
    capabilities: ['market-research', 'scenario-analysis', 'risk-analysis'],
    tools: ['quant-research', 'market-data'],
    constraints: ['research-and-simulation-only', 'no-order-execution'],
    requiresHumanApprovalFor: ['financial-recommendation'],
  },
  {
    id: 'fcx-sports-quant-agent',
    name: 'FCX Sports Quant Agent',
    role: 'specialist',
    domain: 'sports',
    capabilities: ['sports-modeling', 'backtest-analysis', 'probability-analysis'],
    tools: ['sports-datasets', 'quant-research'],
    constraints: ['research-and-simulation-only', 'no-betting-execution'],
    requiresHumanApprovalFor: ['external-publication'],
  },
  {
    id: 'fcx-electronics-lab-agent',
    name: 'FCX Electronics Lab Agent',
    role: 'specialist',
    domain: 'electronics',
    capabilities: ['gateway-diagnostics', 'sensor-analysis', 'modbus-analysis', 'lab-checklists'],
    tools: ['integrations', 'acquisition', 'knowledge'],
    constraints: ['must-include-safety-warning', 'no-unsafe-electrical-procedure'],
    requiresHumanApprovalFor: ['electrical-intervention', 'firmware-deployment'],
  },
  {
    id: 'fcx-knowledge-vault-agent',
    name: 'FCX Knowledge Vault Agent',
    role: 'specialist',
    domain: 'knowledge',
    capabilities: ['document-retrieval', 'evidence-synthesis', 'source-validation'],
    tools: ['knowledge', 'documents'],
    constraints: ['must-cite-sources', 'must-declare-missing-evidence'],
    requiresHumanApprovalFor: ['controlled-document-publication'],
  },
];
