server {
  listen 80;
  server_name app.nexusiotenergy.com.br;
  location / { proxy_pass http://frontend:80; }
}
server {
  listen 80;
  server_name api.nexusiotenergy.com.br;
  location / { proxy_pass http://backend:3000; }
}
server {
  listen 80;
  server_name grafana.nexusiotenergy.com.br;
  location / { proxy_pass http://grafana:3000; }
}
