export const MT100_DEMO_ASSET = {
  id: 'mt100',
  name: 'Compressor MT100',
  type: 'Compressor semi-hermético',
  location: 'Sala de Máquinas / Rack 01',
  status: 'operational',
  protocol: 'MQTT',
  topic: 'fcx/telemetry/mt100',
  metrics: ['temperature', 'vibration', 'current', 'power', 'suctionPressure', 'dischargePressure'],
  nome: 'Compressor MT100',
  tipo: 'COMPRESSOR',
  unidade: 'Sala de Máquinas / Rack 01',
  criticidade: 'HIGH',
};

export const MT100_LATEST_TELEMETRY = {
  assetId: MT100_DEMO_ASSET.id,
  asset: MT100_DEMO_ASSET,
  timestamp: new Date().toISOString(),
  protocol: MT100_DEMO_ASSET.protocol,
  topic: MT100_DEMO_ASSET.topic,
  temperature: 32.4,
  vibration: 1.82,
  current: 38.6,
  power: 21.7,
  suctionPressure: 3.2,
  dischargePressure: 14.8,
  temperatura: 32.4,
  vibracao: 1.82,
  corrente: 38.6,
  potencia: 21.7,
  pressaoSuccao: 3.2,
  pressaoDescarga: 14.8,
};
